wandb: false
output_dir: tmp_trainer
run_name: tmp_trainer
learning_rate: 5.0e-05
do_eval: true
do_predict: true
do_train: true
num_train_epochs: 3.0
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
evaluation_strategy: yes
eval_steps: 1

_n_gpu: 1
dataloader_num_workers: 0
debug: false
eval_accumulation_steps: null
fp16: false
fp16_backend: auto
fp16_opt_level: O1
gradient_accumulation_steps: 1
greater_is_better: null
label_smoothing_factor: 0.0
logging_first_step: false
logging_steps: 500
max_grad_norm: 1.0
max_steps: -1
metric_for_best_model: null
no_cuda: false
overwrite_output_dir: false
past_index: -1
per_gpu_eval_batch_size: null
per_gpu_train_batch_size: null
prediction_loss_only: false
remove_unused_columns: true
save_steps: 500
save_total_limit: null
seed: 42
warmup_steps: 0
weight_decay: 0.0
