wandb: false
fast_run: true
output_dir: runs/tmp_trainer
run_name: runs/tmp_trainer
data_dir: /vol/bitbucket/aeg19/re-re/data/rule-reasoning-dataset-V2020.2.4
learning_rate: 5.0e-05
do_eval: true
do_predict: true
do_train: true
num_train_epochs: 100.0
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
evaluation_strategy: yes
eval_steps: 10000
load_best_model_at_end: false
save_steps: 1000

logging_first_step: true
logging_steps: 10